default:
  image: archlinux

.artifacts:
  artifacts:
    paths:
      - public

validate_yaml:
  before_script:
    - pacman -Syu --noconfirm python-nose python-yaml
  script:
    - nosetests

.build:
  extends: .artifacts
  before_script:
    - pacman -Syu --noconfirm python-mako python-yaml
  script:
    - ./asknot-ng.py templates/index.html questions/archlinux.yml
      l10n/fedora/locale --theme archlinux
  after_script:
    - mv build public
    - |
      cat << EOF > public/_redirects
      / /en/ 302
      /index.html /en/index.html 302
      EOF

build:
  extends: .build
  except:
    - archlinux
    - schedules
    - tags

build:secure:
  extends: .build
  tags:
    - secure
  only:
    - archlinux
    - schedules
    - tags

pages:
  tags:
    - secure
  extends: .artifacts
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - pacman -Syu --noconfirm brotli
  script:
    - find public -type f -regex '.*\.\(css\|html\|jpg\|js\|png\|svg\)' -exec
      gzip -k {} +
    - find public -type f -regex '.*\.\(css\|html\|jpg\|js\|png\|svg\)' -exec
      brotli {} +
  only:
    - archlinux
